- pkg/lib/fieldgroups/securityscanner/securityscanner.go
`SECURITY_SCANNER_V4_NAMESPACE_WHITELIST` should be a `[]string`.
> Type Fix for Security Scanner FieldGroup

- pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
Adds `FieldGroup` struct definition for `DISTRIBUTED_STORAGE_*` section of Quay config. Includes custom `MarshalJSON`/`UnmarshalJSON` methods in order to handle the "unique" tuple nature of the fields (`[string, object]`). Does not implement the constructor or validation.
Seen working here: https://play.golang.org/p/8OHvfLAh1zQ
> Distributed Storage Field Group

- pkg/lib/fieldgroups/database/database.go
Adds `omitempty` tag to the struct field for `DB_CONNECTION_ARGS`. Without this, it marshals to `null` which Quay can't handle on startup.
Blocks https://github.com/quay/quay-operator/pull/13
> Add `omitempty` to Database Field

- pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
Quay fails with the default nil arguments for `DISTRIBUTED_STORAGE_CONFIG`. Add `omitempty` to the JSON tags for those structs.
**Error log from Quay**:
```sh
Traceback (most recent call last):
File "/quay-registry/conf/init/data_migration.py", line 3, in <module>
from app import app
File "/quay-registry/app.py", line 237, in <module>
storage = Storage(app, chunk_cleanup_queue, instance_keys, config_provider, ip_resolver)
File "/quay-registry/storage/__init__.py", line 62, in __init__
app, chunk_cleanup_queue, instance_keys, config_provider, ip_resolver
File "/quay-registry/storage/__init__.py", line 71, in init_app
location, chunk_cleanup_queue, config_provider, ip_resolver, storage_params,
File "/quay-registry/storage/__init__.py", line 39, in get_storage_driver
return …
```
> Omit Empty Fields in Distributed Storage

- pkg/lib/editor/js/core-config-setup/config-setup-tool.html
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1029
**Changelog:** Use Clair v4 fields in editor UI.
**Docs:** N/A
**Testing:** N/A
**Details:** This config tool will only be used to validate Clair v4, so switch to showing fields for v4 rather than v2.
> Editor Exposes Clair v4 Fields (PROJQUAY-1029)

- .air.toml
- Makefile
- commands/editor.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1064
**Changelog:** Switch `--configDir` and `--operatorEndpoint` to use `--kebab-case`.
**Docs:** N/a
**Details:** Switches command-line flags to use `--kebab-case`.
> Switch CLI Flags to Kebab-Case (PROJQUAY-1064)

- pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
This function was removed in `ec95196e498588f96fbf2188d2c890328c6aacbb` for some reason.
> Fix Unmarshal JSON for Distributed Storage FieldGroup

- commands/editor.go
- pkg/lib/editor/editor.go
- pkg/lib/editor/js/config-field-templates/config-bool-field.html
- pkg/lib/editor/js/config-field-templates/config-file-field.html
- pkg/lib/editor/js/config-field-templates/config-numeric-field.html
- pkg/lib/editor/js/config-field-templates/config-password-field.html
- pkg/lib/editor/js/config-field-templates/config-string-field.html
- pkg/lib/editor/js/config-field-templates/config-string-list-field.html
- pkg/lib/editor/js/core-config-setup/config-setup-tool.html
- pkg/lib/editor/js/core-config-setup/core-config-setup.js
- pkg/lib/editor/js/services/api-service.js
- pkg/lib/fieldgroups/database/database.go
- pkg/lib/fieldgroups/database/database_validator.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-909
**Changelog:** Allow passing `--readonly-fieldgroups` to config editor.
**Docs:** N/a
**Testing:** TODO(alecmerdler)
**Details:** Adds `--readonly-fieldgroups` flag to config editor. Primarily will be used by Quay Operator to indicate in the editor UI that managed components are responsible for their config fields.
> Read-Only FieldGroups for Config Editor (PROJQUAY-909)

- pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
- utils/generate/not-done.json
- utils/generate/schema.json
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1087
**Changelog:** Adds the `FEATURE_PROXY_STORAGE` field.
**Docs:** N/a
**Details:** This field is needed to enable storage proxy through the Quay NGINX for https://issues.redhat.com/browse/PROJQUAY-1087.
> Storage Proxy Field (PROJQUAY-1087)

- .env
- Makefile
- pkg/lib/editor/editor.go
- TLS has been added to config-tool
**Docs:** 
- A user should add the following flags to their Docker run command in order to configure TLS.
-v ./testdata-tls/localhost.crt:${CONFIG_TOOL_PUBLIC_KEY} \
-v ./testdata-tls/localhost.key:${CONFIG_TOOL_PRIVATE_KEY} \
-e CONFIG_TOOL_PUBLIC_KEY=${CONFIG_TOOL_PUBLIC_KEY} \
-e CONFIG_TOOL_PRIVATE_KEY=${CONFIG_TOOL_PRIVATE_KEY} 
First, we give the container access to your TLS files through a mounted volume. Then, we specify the internal mount location.
**Testing:** 
**Details:** 
------
> Adding TLS

- pkg/lib/editor/controllers.go
- pkg/lib/editor/js/core-config-setup/config-setup-tool.html
- pkg/lib/editor/js/core-config-setup/core-config-setup.js
- pkg/lib/editor/js/services/api-service.js
- The config editor will now display a warning when no config bundle is found. This replaces the behavior of failing and returning an error. This handles the situation in which new users do not have a valid config bundle yet but still need to access the config editor. 
- Removed logo url and registry short name from being required. 
**Docs:** 
**Testing:** 
**Details:** 
------
> Handle Empty Config Mount (Setup)

- pkg/lib/fieldgroups/gitlabbuildtrigger/gitlabbuildtrigger.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1161
- Set default Gitlab endpoint to https://gitlab.com. This ensures that a gitlab endpoint is present even when a user is not prompted for an explicit url in the ui
**Docs:** 
**Testing:** 
**Details:** 
------
> set default gitlab endpoint

- .github/workflows/go.yml
- pkg/lib/editor/js/core-config-setup/config-setup-tool.html
- pkg/lib/fieldgroups/database/database_test.go
- pkg/lib/fieldgroups/database/database_validator.go
**Issue:**
- https://issues.redhat.com/browse/PROJQUAY-1149
**Changelog:**
- Use `mysql+pymysql://` for MySQL's DB_URI
**Docs:** 
- n/a
**Testing:**
- The `config.yaml` generated by the config-tool should allow Quay to successfully connect to a MySQL server.
**Details:** 
- Quay currently requires the Python library `pymysql` to be explicitly mentioned when defining the connection string for MySQL.
> [PROJQUAY-1149] fix: Use mysql+pymysql:// for MySQL DB_URI

- pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
- pkg/lib/shared/validators.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1189
- Fixed S3 port issue. Port parsing can now accept a valid string, a float64, or an integer. 
- Set default S3 endpoint to s3.amazonaws.com
**Docs:** 
**Testing:** 
**Details:** 
------
> Fix s3 port issue

- pkg/lib/editor/js/core-config-setup/config-setup-tool.html
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1198
Removed reference to deprecated features rkt and v1 push
**Docs:** 
Removed reference to deprecated features rkt and v1 push
**Testing:** 
Confirm visually that config editor does not show or reference rkt or v1 push
**Details:** 
Removed UI components of deprecated features. Code removal will happen after 3.4.
> PROJQUAY-1198 - remove deprecated editor fields

- pkg/lib/editor/js/core-config-setup/core-config-setup.js
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1202
pkg/lib/editor/js/core-config-setup/core-config-setup.js
**Docs:** 
**Testing:** 
Starting a new idle 3.4 Quay container, connection counts should not continue to rise but stay flat (~15).
**Details:** 
Database connections for some workers not being released automatically since the config value TESTING defaults to 'true' in Quay code.  This fix overrides the default to 'false' in the config bundle to match how it works in Quay 3.3.
> Added default TESTING=false to match old Config App

- pkg/lib/editor/controllers.go
- pkg/lib/editor/editor.go
- pkg/lib/editor/js/core-config-setup/core-config-setup.js
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1156
**Changelog:** Fix `managedFieldGroups` not being sent to Operator reconfigure endpoint.
**Docs:** N/a
**Details:** Fixes TNG Operator reconfigure JSON payload.
> Fix Kubernetes Reconfigure Endpoint (PROJQUAY-1156)

- pkg/lib/shared/validators.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1324
- Config-tool will check if a port is appended to a hostname and remove it before validating that name against an SSL certificate. 
**Docs:** 
**Testing:** 
**Details:** 
------
> Removed port is cert hostname validation

- pkg/lib/fieldgroups/signingengine/signingengine.go
- pkg/lib/fieldgroups/signingengine/signingengine_fields.go
- pkg/lib/fieldgroups/signingengine/signingengine_test.go
- pkg/lib/fieldgroups/signingengine/signingengine_validator.go
- utils/generate/schema.json
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1310
- Config-tool will now read the FEATURE_SIGNING flag and skip signing engine validation if false.
- FEATURE_SIGNING flag will default to false
**Docs:** 
**Testing:** 
- Unit tests for validation function added
**Details:** 
------
> Added feature signing flag and skip validation when true

- pkg/lib/fieldgroups/ldap/ldap.go
- pkg/lib/fieldgroups/ldap/ldap_test.go
- pkg/lib/fieldgroups/ldap/ldap_validator.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1272
- Use ldap config values to query server and ensure that users exist (for validation)
- Added test cases
**Docs:** 
**Testing:** 
- Added test cases using external live test server
**Details:**
> Added query to check users in ldap exist

- pkg/lib/editor/controllers.go
- pkg/lib/editor/js/components/file-upload-box.html
- pkg/lib/editor/js/components/file-upload-box.js
- pkg/lib/editor/js/config-field-templates/config-certificates-field.html
- pkg/lib/editor/js/core-config-setup/config-setup-tool.html
- pkg/lib/editor/js/core-config-setup/core-config-setup.js
- pkg/lib/editor/static/css/core-ui.css
- pkg/lib/editor/static/css/quay.css
- **Fixed CSS on modals for validation errors**
- **Added proper modal for Quay reconfigure endpoint**
- **Fixed upload certificate box. Bad certs will be uploaded and the error message will be shown under 'status'. The user can also now delete certificates that they have uploaded.**
- **Removed alert and replaced with below modal when a user loads config-app without a config bundle. This sets up a setup session with defaults**
**Docs:** 
**Testing:** 
**Details:** 
------
> Fixed modals

- commands/validate.go
- pkg/lib/shared/storage_validators.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1307
- Config tool will now validate Swift storage v3 auth. It will also ensure that the listed container is in fact present.
- Added clearer error message in `validate` command CLI output when type errors are found during `config.yaml` unmarshalling
**Docs:** 
**Testing:** 
**Details:** 
------
> validation tested and working on swift authv3

- pkg/lib/editor/js/core-config-setup/core-config-setup.js
- pkg/lib/shared/storage_validators.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1306
**Changelog:** Fix CloudFront storage validation.
**Docs:** N/a
**Details:** The validation logic for CloudFront S3 storage was incorrectly using the public key ID (`cloudfront_key_id`) as the distribution ID when looking up the CloudFront distribution. As the distribution ID is not a field in `config.yaml`, instead change the logic to list distributions and search for one which matches the provided `cloudfront_distribution_domain`. Also check that there is a public key for the given `cloudfront_key_id`.
> Fix CloudFront Validation (PROJQUAY-1306)

- pkg/lib/fieldgroups/timemachine/timemachine_validator.go
- pkg/lib/shared/validators.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1262
- Updated error message for default tag expiration option not being contained as one of the allowed expiration options.
**Docs:** 
**Testing:** 
**Details:** 
------
> fixed error message for default tag expiration options

- pkg/lib/editor/js/core-config-setup/core-config-setup.js
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1561
- Config editor sets `ca` field to `/conf/stack/database.pem` when uploading a cert for mysql/postgres
**Docs:** 
**Testing:** 
**Details:** 
------
> PROJQUAY-1561

- pkg/lib/generate/generate.go
- pkg/lib/generate/generate_test.go
- Added function that will generate a `config.Config` struct given the minimum required fields. The minimum required fields are currently the DB_URI, REDIS_HOSTNAME, REDIS_PASSWORD, and SERVER_HOSTNAME. 
**Docs:** 
**Testing:** 
**Details:** 
------
> AIOI Generate Base Config Function

- pkg/lib/editor/controllers.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1577
**Changelog:** Do not strip out `HostSettings` fieldgroup when submitting to Operator.
**Docs:** N/a
**Testing:** Use config editor to reconfigure with Operator and ensure that `SERVER_HOSTNAME` is unchanged.
**Details:** The `HostSettings` field group is unique because it can be marked as managed, but we allow users to set the `SERVER_HOSTNAME` and provide their own TLS cert/key pair.
> Keep `HostSettings` Fieldgroup Intact during Operator Reconfigure

- pkg/lib/editor/js/core-config-setup/core-config-setup.js
Make sure USERFILES_LOCATION is set to an existing storage instead of
always using "default".
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1742
- Make sure USERFILES_LOCATION is set to an existing storage instead of
always using "default".
**Docs:** 
**Testing:** 
**Details:**
> frontend: Set default USERFILES_LOCATION to a valid storage

- pkg/lib/fieldgroups/oidc/oidc_validator.go
Use the custom client context to ensure self-signed certificates can be used when validating OIDC providers.
> OIDC Validation Client Context

- pkg/lib/fieldgroups/email/email.go
- pkg/lib/fieldgroups/email/email_validator.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1804
- Add validation check for `MAIL_USE_TLS` enabled when `FEATURE_FIPS` is enabled
**Docs:** 
**Testing:** 
**Details:** 
------
> Ensure mail tls is enabled when running in fips mode

- pkg/lib/fieldgroups/ldap/ldap_validator.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1963
- Only query one page of users from the LDAP server to check if existing users present. This prevents the server from timing out on large LDAP requests. 
**Docs:** 
**Testing:** 
**Details:** 
------
> Only query one page of users to check for existing users

- pkg/lib/fieldgroups/securityscanner/securityscanner_validator.go
Clair v4 will refuse connections to the main app port until the
vulnerability database is fully initialized. This should not block
Quay's validation, so we point to Clair's introspection server to
validate instead (which accepts connections during init).
Signed-off-by: Alec Merdler <alecmerdler@gmail.com>
> securityscanner: validate introspection endpoint (PROJQUAY-1610)

- pkg/lib/fieldgroups/redis/redis.go
- pkg/lib/fieldgroups/redis/redis_validator.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-2149
Adding support for SSL in the redis config validator
> PROJQUAY-2149: Add SSL to build log and user event Redis config

- .env
- pkg/lib/editor/js/core-config-setup/core-config-setup.js
- pkg/lib/fieldgroups/database/database.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1815
- Added regex to normalized date string returned by x509 library. This ensures that the expiration date is parsed correctly.
- Replaced hard coded CT_DIR variable to $PWD
**Docs:** 
**Testing:** 
**Details:** 
------
> Normalize 'notAfter' string returned by x509 library

- Makefile
- pkg/lib/editor/js/core-config-setup/config-setup-tool.html
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1998
- A deprecation warning is now shown when a user has MySQL selected in the config editor
**Docs:** 
**Testing:** 
**Details:** 
------
> (PROJQUAY-1998) Added deprecation warning on MySQL

- pkg/lib/editor/js/core-config-setup/core-config-setup.js
**Issue:** https://issues.redhat.com/browse/PROJQUAY-2200
- Add 'sslmode=verify-full' to DB_CONNECTION_ARGS when Postgres cert is uploaded from the config editor
**Docs:** 
**Testing:** 
**Details:** 
------
> editor: Add sslmode=verify-full when Postgres cert uploaded (PROJQUAY-2200)

- pkg/lib/shared/functions.go
Avoid attempting to load private keys. By loading private keys
AppendCertsFromPEM() fails, it only accepts CERTIFICATES.
> configvalidation: load only certificates (PROJQUAY-2416)

- pkg/lib/editor/js/core-config-setup/config-setup-tool.html
To better reflect the option this commit changes the option presented to
the user. Instead of informing users that Quay pod would be responsible
for terminating the TLS we now inform users that they can provide custom
TLS certificates.
We still do the TLS termination at the load balancer level but this time
using user provided certificates.
> tlscomponent: changing option message for custom tls (PROJQUAY-2428)

- pkg/lib/editor/js/core-config-setup/config-setup-tool.html
The link to creating a new application in gitlab
was fixed
Signed-off-by: harishsurf <hgovinda@redhat.com>
**Issue:** https://issues.redhat.com/browse/PROJQUAY-2449
> href: Fix broken link (PROJQUAY-2449)

- pkg/lib/shared/functions.go
Avoid attempting to load private keys. By loading private keys
AppendCertsFromPEM() fails, it only accepts CERTIFICATES.
(cherry picked from commit e7fef0e80385a6a06a32d3d009e37311936320fa)
> configvalidation: load only certificates (PROJQUAY-2416) (#118)

- pkg/lib/fieldgroups/database/database_validator.go
- pkg/lib/shared/validators.go
Temporarily write the root pem to "/tmp". This allows the config-tool
to set sslrootcert to "/tmp/database.pem" in order to validate the
cert when pinging the postgres.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-2414
> validation: fix postgres root cert validation (PROJQUAY-2414)

- pkg/lib/fieldgroups/database/database_validator.go
- pkg/lib/shared/validators.go
Temporarily write the root pem to "/tmp". This allows the config-tool
to set sslrootcert to "/tmp/database.pem" in order to validate the
cert when pinging the postgres.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-2414
-Fix postgres certificate validation
Cherrypicked from 04973cc
> validation: fix postgres root cert validation (PROJQUAY-2414) (#113)

- pkg/lib/shared/functions.go
Due to AppendCertsFromPEM failing when getting .key files
a change was made to stop loading them, this broke the ssl validation
that expects ssl.key and ssl.cert. This change adds back the .key file
loading and just warns if AppendCertsFromPEM cannot load the file
instead of erroring.
Signed-off-by: crozzy <joseph.crosland@gmail.com>
**Issue:** https://issues.redhat.com/browse/PROJQUAY-2511
Due to AppendCertsFromPEM failing when getting .key files
a change was made to stop loading them, this broke the ssl validation
that expects ssl.key and ssl.cert. This change adds back the .key file
loading and just warns if AppendCertsFromPEM cannot load the file
instead of erroring.
**Docs:** 
**Testing:** 
None
**Details:**
> PROJQUAY-2511 - ssl: re-enable .key file loading (PROJQUAY-2511)

- pkg/lib/shared/functions.go
Due to AppendCertsFromPEM failing when getting .key files
a change was made to stop loading them, this broke the ssl validation
that expects ssl.key and ssl.cert. This change adds back the .key file
loading and just warns if AppendCertsFromPEM cannot load the file
instead of erroring.
Signed-off-by: crozzy <joseph.crosland@gmail.com>
**Docs:** 
**Testing:** 
**Details:** 
------
(_This section may be deleted._)
**All fields are required.** If a field is not applicable (eg. no relevant CHANGELOG.md), specify "none" or "n/a".
Issue: This is the PROJQUAY jira reference. Pull-request title must start with issue name "PROJQUAY-1234 - ".
Changelog: One line description …
> ssl: re-enable .key file loading (PROJQUAY-2511)

- pkg/lib/editor/js/core-config-setup/config-setup-tool.html
**Issue:** https://issues.redhat.com/browse/PROJQUAY-2489
- Add logic to remove the RepoMirror component from fieldGroupsReadonly in the ui
**Docs:** 
**Testing:** 
**Details:** 
------
> editor: Add logic to allow managing/unmanaging of RepoMirror from ui

- pkg/lib/editor/js/core-config-setup/config-setup-tool.html
- pkg/lib/editor/js/core-config-setup/core-config-setup.js
**Issue:** https://issues.redhat.com/browse/PROJQUAY-2528
- Remove certs from ui scope when selecting external tls or no tls
- Only show "None" option when in non-operator deployment
**Docs:** 
**Testing:** 
**Details:** 
------
> editor: Remove certs from ui scope on select external-tls (PROJQUAY-2628)

- pkg/lib/shared/storage_validators.go
- Remove storage_path as a required field
> storage: Do not require a storage_path in Distributed Storage Configuration

- pkg/lib/shared/validators.go
The user count check fails whenever quay is loaded for the first time
and there are no users present. This PR removes the validation
Signed-off-by: harishsurf <hgovinda@redhat.com>
> ldap: Remove validation check for users (PROJQUAY-2343)

- pkg/lib/shared/validators.go
The check fails whenever quay is loaded for the first time
and there are no users present
Signed-off-by: harishsurf <hgovinda@redhat.com>
(cherry picked from commit acc3748236b3123fa3ab55faf1d5061eb5d4293c)
> ldap: Remove validation check for users (PROJQUAY-2343) (#142)

- pkg/lib/shared/storage_validators.go
When the access and secret key aren't passed during s3 storage validation it will fall back to using ec2 role auth. This will fail with `The AWS Access Key Id you provided does not exist in our records.`. This fix passes the session token so that the auth to s3 can succeed.
> s3validation: Pass token during ec2 role auth (PROJQUAY-2983)

- Dockerfile
- Dockerfile.dev
- pkg/lib/editor/js/core-config-setup/core-config-setup.js
- pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
- pkg/lib/shared/storage_validators.go
- pkg/lib/shared/structs.go
Allows overriding the Azure storage endpoint, as an example `accountname.blob.core.usgovcloudapi.net`.
> configtool: Add option to override Azure endpoint (PROJQUAY-891)

- pkg/lib/shared/storage_validators.go
Error messages returned by Azure were being parsed in the wrong format. This removes that parsing and returns only the error.
> azure: Remove parsing of error response (PROJQUAY-3718)

- pkg/lib/shared/validators.go
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1605
- Use TLS certs when connecting to smtp instead of plain auth
**Docs:** 
**Testing:** 
**Details:** 
------
> smtp: Use TLS certs when connecting to smpt (PROJQUAY-1605)

- Dockerfile
- Dockerfile.dev
- go.mod
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1605
- Update golang version from 1.14 to 1.16
**Docs:** 
**Testing:** 
**Details:** 
------
> go: Update golang to version 1.16 (PROJQUAY-1605)

- README.md
**Issue:** https://issues.redhat.com/browse/PROJQUAY-4558
- Add documentation to readme on how to provide TLS certs to config tool runtime
> docs: Add documentation for TLS usage (PROJQUAY-4558)

- .github/workflows/release.yml
- .github/workflows/update-quay.yml
Currently `${{ github.event.inputs.tag }}` resolves into an empty string, so the GitHub workflow creates PRs like https://github.com/quay/quay/pull/1999.
This PR makes the pull-request-quay job to run only when a new tag is pushed.
> chore: Create PR against Quay for new tags
