quay/config-tool

pkg/lib/fieldgroups/accesssettings/accesssettings.go
pkg/lib/fieldgroups/actionlogarchiving/actionlogarchiving.go
pkg/lib/fieldgroups/apptokenauthentication/apptokenauthentication.go
pkg/lib/fieldgroups/bitbucketbuildtrigger/bitbucketbuildtrigger.go
pkg/lib/fieldgroups/database/database.go
pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
pkg/lib/fieldgroups/elasticsearch/elasticsearch.go
pkg/lib/fieldgroups/githubbuildtrigger/githubbuildtrigger.go
pkg/lib/fieldgroups/githublogin/githublogin.go
pkg/lib/fieldgroups/gitlabbuildtrigger/gitlabbuildtrigger.go
pkg/lib/fieldgroups/googlelogin/googlelogin.go
pkg/lib/fieldgroups/jwtauthentication/jwtauthentication.go
pkg/lib/fieldgroups/quaydocumentation/quaydocumentation.go
pkg/lib/fieldgroups/redis/redis.go
pkg/lib/fieldgroups/securityscanner/securityscanner.go
pkg/lib/fieldgroups/signingengine/signingengine.go
pkg/lib/fieldgroups/teamsyncing/teamsyncing.go
pkg/lib/fieldgroups/uservisiblesettings/uservisiblesettings.go

Adds equivalent `json:` struct tags for `FieldGroups` which mirror the `yaml:` tags.

JSON Struct Tags

---

pkg/lib/fieldgroups/hostsettings/hostsettings.go

Adds `json` struct tags for this field group.

HostSettings FieldGroup JSON Tags

---

pkg/lib/editor/editor.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-NA
- Added wrappers around http handlers to take config mount path. 
**Docs:** 
**Testing:** 
**Details:** 
------

Remove Hardcoded Config Mount Path

---

pkg/lib/config/config.go
pkg/lib/fieldgroups/repomirror/repomirror.go
pkg/lib/fieldgroups/repomirror/repomirror_fields.go
pkg/lib/fieldgroups/repomirror/repomirror_test.go
pkg/lib/fieldgroups/repomirror/repomirror_validator.go
utils/generate/not-done.json
utils/generate/schema.json

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1060
- added field group for repo mirroring
**Docs:** 
**Testing:** 
- added unit tests for NewRepoMirrorFieldGroup and validation
**Details:** 
------

PROJQUAY-1060

---

.env
Makefile
pkg/lib/editor/editor.go
pkg/lib/editor/js/services/api-service.js
pkg/lib/shared/functions.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1066
- Download endpoint includes newly uploaded certs
- Tar file has correct structure (ex. extra_ca_certs folder)
**Docs:** 
**Testing:** 
**Details:** 
------

PROJQUAY-1066

---

pkg/lib/fieldgroups/securityscanner/securityscanner.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1107
**Changelog:** Updates needed for Quay security scanner notifications.
**Docs:** N/a
**Details:** Changes to the fielgroups and config for security scanner notifications.

Security Scanner Notifications (PROJQUAY-1107)

---

pkg/lib/fieldgroups/database/database_test.go
pkg/lib/fieldgroups/database/database_validator.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1024
- added check for pg_trgm extension in postgres database
**Docs:** 
**Testing:** 
**Details:** 
------

Check pg_trgm extension in Postgres validation

---

pkg/lib/editor/controllers.go

- Null value removal was included in CLI steps but not in API steps. This PR fixes that to ensure that null values are removed in the API as well. 
**Docs:** 
**Testing:** 
**Details:** 
------

Add Null Fix to Api Endpoint

---

commands/validate.go

- Bug fix to add loading certs in cli (previously were only loaded in api call)
**Docs:** 
**Testing:** 
**Details:** 
------

added cert loading to cli

---

pkg/lib/fieldgroups/accesssettings/accesssettings.go
pkg/lib/fieldgroups/actionlogarchiving/actionlogarchiving.go
pkg/lib/fieldgroups/apptokenauthentication/apptokenauthentication.go
pkg/lib/fieldgroups/bitbucketbuildtrigger/bitbucketbuildtrigger.go
pkg/lib/fieldgroups/database/database.go
pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
pkg/lib/fieldgroups/elasticsearch/elasticsearch.go
pkg/lib/fieldgroups/githubbuildtrigger/githubbuildtrigger.go
pkg/lib/fieldgroups/githublogin/githublogin.go
pkg/lib/fieldgroups/gitlabbuildtrigger/gitlabbuildtrigger.go
pkg/lib/fieldgroups/googlelogin/googlelogin.go
pkg/lib/fieldgroups/hostsettings/hostsettings.go
pkg/lib/fieldgroups/jwtauthentication/jwtauthentication.go
pkg/lib/fieldgroups/quaydocumentation/quaydocumentation.go
pkg/lib/fieldgroups/redis/redis.go
pkg/lib/fieldgroups/repomirror/repomirror.go
pkg/lib/fieldgroups/securityscanner/securityscanner.go
pkg/lib/fieldgroups/signingengine/signingengine.go
pkg/lib/fieldgroups/teamsyncing/teamsyncing.go
pkg/lib/fieldgroups/uservisiblesettings/uservisiblesettings.go

**Docs:** 
**Testing:** 
**Details:** 
------

Added omitempty tags to all fields

---

pkg/lib/editor/js/core-config-setup/config-setup-tool.html
pkg/lib/editor/js/core-config-setup/core-config-setup.js
pkg/lib/fieldgroups/securityscanner/securityscanner.go
utils/generate/schema.json

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1106
- Added Sign JWT and PSK fields in config editor ui
- Added button to generate base64 key for PSK
**Docs:** 
**Testing:** 
**Details:** 
blocked by: https://github.com/quay/quay/pull/554 
------

Security Scanner PSK - Config Tool

---

pkg/lib/editor/controllers.go
pkg/lib/editor/js/core-config-setup/config-setup-tool.html
pkg/lib/editor/js/core-config-setup/core-config-setup.js
pkg/lib/editor/js/services/api-service.js
pkg/lib/fieldgroups/securityscanner/securityscanner_test.go
pkg/lib/fieldgroups/securityscanner/securityscanner_validator.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1137
**Docs:** 
**Testing:** 
**Details:** 
------
(_This section may be deleted._)
**All fields are required.** If a field is not applicable (eg. no relevant CHANGELOG.md), specify "none" or "n/a".
Issue: This is the PROJQUAY jira reference. Pull-request title must start with issue name "PROJQUAY-1234 - ".
Changelog: One line description to be added to CHANGELOG.md during release builds. Typically starts with "Added:", "Fixed:", "Note:", etc.
Docs: Detailed description of changes necessary to docs.projectquay.io. Examples would be addition of config.yaml, indication of UI changes and screenshot impact, and changes in behavior of features.
Testing: Detailed description of how to test changes manually. This section …

Added setup variable, fixed clair setup

---

pkg/lib/editor/js/core-config-setup/core-config-setup.js
pkg/lib/editor/package-lock.json
pkg/lib/editor/package.json

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1140
- Config app generates setup complete and db secret key values on a successful validation in a setup session
**Docs:** 
**Testing:** 
**Details:** 
------

added setup complete, db secret key

---

pkg/lib/editor/js/core-config-setup/config-setup-tool.html

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1138
**Docs:** 
**Testing:** 
**Details:** 
------

Add Super Users field to ui

---

pkg/lib/editor/editor.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1075
- Includes logging middleware when DEBUGLOG variable is set 
**Docs:** 
**Testing:** 
**Details:** 
------

Added DEBUGLOG var

---

commands/print.go
pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
pkg/lib/fieldgroups/distributedstorage/distributedstorage_validator.go
pkg/lib/shared/structs.go
pkg/lib/shared/validators.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1153
- Fixed validation for S3 storage
**Docs:** 
**Testing:** 
**Details:** 
------

Fix S3 Storage + Azure

---

pkg/lib/editor/controllers.go
pkg/lib/editor/js/core-config-setup/core-config-setup.js
pkg/lib/editor/js/services/api-service.js

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1136
- Fixed tarball download not automatically pushing data + yaml output
**Docs:** 
**Testing:** 
**Details:** 
------

Fix Tarball Download

---

Makefile
pkg/lib/shared/functions.go

- Fixed panic on empty cert dir when setup mode is initialized
**Docs:** 
**Testing:** 
**Details:** 
------

Fix cert panic on empty dir

---

Makefile
pkg/lib/config/config.go
pkg/lib/fieldgroups/email/email_fields.go
pkg/lib/fieldgroups/timemachine/timemachine.go
pkg/lib/fieldgroups/timemachine/timemachine_fields.go
pkg/lib/fieldgroups/timemachine/timemachine_test.go
pkg/lib/fieldgroups/timemachine/timemachine_validator.go
pkg/lib/shared/functions.go
utils/generate/not-done.json
utils/generate/schema.json

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1204
- Added defaults for tag expiration
- Created time machine field groups
- Added validation for default tag expiration
**Docs:** 
**Testing:** 
**Details:** 
------

Added time machine default settings

---

pkg/lib/fieldgroups/securityscanner/securityscanner_test.go
pkg/lib/fieldgroups/securityscanner/securityscanner_validator.go
pkg/lib/shared/functions.go
pkg/lib/shared/storage_validators.go
pkg/lib/shared/validators.go

- Removed function that blocked tcp dial timeout
- Refactored tls.Config struct creation into separate function
**Docs:** 
**Testing:** 
**Details:** 
------

TLS Dial Timeout

---

pkg/lib/shared/validators.go

**Docs:** 
**Testing:** 
**Details:** 
------

append error message to tcp dial failure

---

pkg/lib/shared/storage_validators.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1216
- Add check that bucket name exists in storage type
- Fail validation when bucket does not exist
**Docs:** 
**Testing:** 
**Details:** 
------

Check bucket exists in Minio gateway validation

---

go.mod
go.sum
pkg/lib/config/config.go
pkg/lib/fieldgroups/ldap/ldap.go
pkg/lib/fieldgroups/ldap/ldap_fields.go
pkg/lib/fieldgroups/ldap/ldap_test.go
pkg/lib/fieldgroups/ldap/ldap_validator.go
utils/generate/schema.json

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1257
- Fixed issue with LDAP not being verified correctly 
- Added LDAP CA cert to connection pool when attempting to connect to LDAP
**Docs:** 
**Testing:** 
**Details:** 
------

fixed ldap validation

---

pkg/lib/editor/js/core-config-setup/core-config-setup.js

**Docs:** 
**Testing:** 
**Details:** 
------

Fixed errorDisplay js bug

---

go.mod
go.sum
pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
pkg/lib/shared/storage_validators.go
pkg/lib/shared/structs.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1222
- Fixed cloudfront validation to validate all s3 settings as well as checking for a valid domain and id
**Docs:** 
**Testing:** 
**Details:** 
------

Fixed cloudfront -> validates all s3 settings + domain and id

---

go.mod
go.sum
pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
pkg/lib/shared/storage_validators.go
pkg/lib/shared/structs.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1307
- Added v1 auth to validation for swift storage
**Docs:** 
**Testing:** 
- Tested with SAIO v1 image. Need testing for v2 and v3
**Details:** 
------

[WIP] Added v1 auth to Swift Storage Validation

---

pkg/lib/fieldgroups/accesssettings/accesssettings.go
pkg/lib/fieldgroups/actionlogarchiving/actionlogarchiving.go
pkg/lib/fieldgroups/apptokenauthentication/apptokenauthentication.go
pkg/lib/fieldgroups/bitbucketbuildtrigger/bitbucketbuildtrigger.go
pkg/lib/fieldgroups/database/database.go
pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
pkg/lib/fieldgroups/elasticsearch/elasticsearch.go
pkg/lib/fieldgroups/email/email.go
pkg/lib/fieldgroups/githubbuildtrigger/githubbuildtrigger.go
pkg/lib/fieldgroups/githublogin/githublogin.go
pkg/lib/fieldgroups/gitlabbuildtrigger/gitlabbuildtrigger.go
pkg/lib/fieldgroups/googlelogin/googlelogin.go
pkg/lib/fieldgroups/hostsettings/hostsettings.go
pkg/lib/fieldgroups/jwtauthentication/jwtauthentication.go
pkg/lib/fieldgroups/ldap/ldap.go
pkg/lib/fieldgroups/repomirror/repomirror.go
pkg/lib/fieldgroups/securityscanner/securityscanner.go
pkg/lib/fieldgroups/signingengine/signingengine.go
pkg/lib/fieldgroups/teamsyncing/teamsyncing.go
pkg/lib/fieldgroups/timemachine/timemachine.go
pkg/lib/shared/structs.go

- Golang treats false as 0 values and will omit them from json unmarshal. since this behavior will remove set boolean values, they will always be unmarshalled. 
- In future, this will be solved by changing to boolean pointers
**Docs:** 
**Testing:** 
**Details:** 
------

Removed omitempty from bool value tags

---

pkg/lib/editor/controllers.go
pkg/lib/editor/js/config-field-templates/config-file-field.html
pkg/lib/editor/js/core-config-setup/config-setup-tool.html
pkg/lib/editor/js/core-config-setup/core-config-setup.js

- Added gzip compression to tarball
- Fixed CSS and error handling with file input fields
**Docs:** 
**Testing:** 
**Details:** 
------

fixed file input field

---

pkg/lib/fieldgroups/email/email.go
pkg/lib/fieldgroups/email/email_validator.go

- Mail validation now dials the smtp server and attempts to log in with the given credentials (if specified)
**Docs:** 
**Testing:** 
**Details:** 
------

Added validation for smtp

---

go.mod
go.sum
pkg/lib/config/config.go
pkg/lib/fieldgroups/accesssettings/accesssettings.go
pkg/lib/fieldgroups/accesssettings/accesssettings_test.go
pkg/lib/fieldgroups/accesssettings/accesssettings_validator.go
pkg/lib/fieldgroups/oidc/oidc.go
pkg/lib/fieldgroups/oidc/oidc_fields.go
pkg/lib/fieldgroups/oidc/oidc_test.go
pkg/lib/fieldgroups/oidc/oidc_validator.go
pkg/lib/shared/functions.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1342
- Added external validation for OIDC configuration. Also added check for this provider in AccessSettings
**Docs:** 
**Testing:** 
- AccessSettingsFieldGroup test checks for OIDC if no other auth types are available
**Details:** 
------

Added additional OIDC validation

---

pkg/lib/editor/js/core-config-setup/config-setup-tool.html

**Issue:** https://issues.redhat.com/browse/PROJQUAY-541
- Links in config-tool will now open in a new tab instead of in the current window. This prevents your progress from being lost when clicking on a hyperlink
**Docs:** 
**Testing:** 
**Details:** 
------

PROJQUAY-541

---

pkg/lib/fieldgroups/database/database_validator.go
pkg/lib/fieldgroups/email/email.go
pkg/lib/fieldgroups/email/email_validator.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-1964
- Use the provided ParseURI function to get db connection options. 
- Fixes Azure connection validation issues. 
**Docs:** 
**Testing:** 
**Details:** 
------

Use ParseURI function to get db connection options

---

pkg/lib/editor/js/core-config-setup/core-config-setup.js
pkg/lib/shared/functions.go

**Docs:** 
**Testing:** 
**Details:** 
------

certs: Load certs with both extra_ca_cert_ and extra_ca_certs/ prefix

---

pkg/lib/fieldgroups/githubbuildtrigger/githubbuildtrigger_validator.go
pkg/lib/fieldgroups/githublogin/githublogin_validator.go
pkg/lib/shared/validators.go

- Add certs to validator call to Github

github: Add custom tls certs to github oauth validator (PROJQUAY-2560)

---

pkg/lib/fieldgroups/githubbuildtrigger/githubbuildtrigger_validator.go
pkg/lib/fieldgroups/githublogin/githublogin_validator.go
pkg/lib/shared/validators.go

**Docs:** 
**Testing:** 
**Details:** 
------
(_This section may be deleted._)
**All fields are required.** If a field is not applicable (eg. no relevant CHANGELOG.md), specify "none" or "n/a".
Issue: This is the PROJQUAY jira reference. Pull-request title must start with issue name "[PROJQUAY-1234](https://issues.redhat.com//browse/PROJQUAY-1234) - ".
Changelog: One line description to be added to CHANGELOG.md during release builds. Typically starts with "Added:", "Fixed:", "Note:", etc.
Docs: Detailed description of changes necessary to docs.projectquay.io. Examples would be addition of config.yaml, indication of UI changes and screenshot impact, and changes in …

Add custom tls certs to github oauth validator (#172)

---

pkg/lib/fieldgroups/githublogin/githublogin_validator.go

- Use GitHubEndpoint config variable

Use github endpoint config var instead of Api endpoint

---

.github/workflows/go.yml
Dockerfile
Dockerfile.dev
go.mod

**Docs:** 
**Testing:** 
**Details:** 
------
(_This section may be deleted._)
**All fields are required.** If a field is not applicable (eg. no relevant CHANGELOG.md), specify "none" or "n/a".
Issue: This is the PROJQUAY jira reference. Pull-request title must start with issue name "[PROJQUAY-1234](https://issues.redhat.com//browse/PROJQUAY-1234) - ".
Changelog: One line description to be added to CHANGELOG.md during release builds. Typically starts with "Added:", "Fixed:", "Note:", etc.
Docs: Detailed description of changes necessary to docs.projectquay.io. Examples would be addition of config.yaml, indication of UI changes and screenshot impact, and changes in …

Cherry pick 1065

---

pkg/lib/shared/validators.go

- Fix path in config tool parsing of extra_ca_certs
**Issue:** https://issues.redhat.com/browse/PROJQUAY-4222
**Docs:** 
**Testing:** 
**Details:** 
------

validator: Fix database.pem path in config.yaml (PROJQUAY-4222)

---

pkg/lib/editor/js/core-config-setup/core-config-setup.js

- Add default oci artifact types to generated config
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1032
**Docs:** 
**Testing:** 
**Details:** 
------

setup: Add ALLOWED_OCI_ARTIFACT_TYPES to generated config (PROJQUAY-1032)

---

pkg/lib/editor/js/core-config-setup/config-setup-tool.html
pkg/lib/editor/js/core-config-setup/core-config-setup.js
pkg/lib/fieldgroups/distributedstorage/distributedstorage.go
pkg/lib/shared/storage_validators.go
pkg/lib/shared/structs.go

**Issue:** https://issues.redhat.com/browse/PROJQUAY-5048
Add CloudFlare and MultiCDN config validation
**Testing:** 
Tested locally

storage: Add CloudFlare and MultiCDN config validation (PROJQUAY-5048)

---

.github/workflows/release.yml

Create a release on push to master

deploy: Add workflow to auto release on push (PROJQUAY-5048)

---

.github/workflows/release.yml

Adding an action to create a PR against quay for auto release
**Issue:** https://issues.redhat.com/browse/PROJQUAY-5048

deploy: Create a PR against quay for every release (PROJQUAY-5048)

---

.github/workflows/release.yml

deploy: fix release.yaml quote ([PROJQUAY-5048](https://issues.redhat.com//browse/PROJQUAY-5048))

deploy: fix release.yaml quote (PROJQUAY-5048)

---

.github/workflows/release.yml

use PAT for creating PR on quay repo ([PROJQUAY-5048](https://issues.redhat.com//browse/PROJQUAY-5048))

deploy: use PAT for creating PR on quay repo (PROJQUAY-5048)
